### ISSUE TITLE
🥹

### ISSUE THREAD

**Issue by fmac2000** [eloimoliner/BABE#2]
Hi Authors,

This paper is really beautiful, thank you. 

I'm thinking of using some of the [old 78s](https://archive.org/details/78_well-meet-again_benny-goodman-and-his-orch-peggy-lee-parker-charles_gbia0105219b) with the restoration technique you displayed in the paper. In your testing, did the vocals maintain quality with this method?

Thank you.

**Comment by eloimoliner** [comment]
Hi,

Thanks you for your intererest!
We don't have a working model for singing voice yet. So far, we have only published trained models for piano, strings, woodwind and brass instruments.
PD: vocal restoration is something I'm partly working on at the moment. Hopefully I'll have the chance to publish a model in the near future.

**Comment by B3AU** [comment]
Hi Eloi! 

Any progress on this? I'm also very keen on testing this to restore old 78s and rare LPs in bad condition. Those would be full bands in almost all cases.

Thanks!

**Comment by eloimoliner** [comment]
Hi!  I'm writing a paper about that at the moment.  The paper will be out in a couple of weeks (hopefully).  It now works much better for the restoration of 78s. For simplicity reasons, I've only focused on solo piano recordings and separated  vocal recordings. However, it may be possible to apply the method to different kinds of content if you fine-tune a diffusion model with a small reference set (a couple of high quality recordings similar to the old one). 
I'll try to prepare a cleaner repository that is easier to use and fine-tune.

**Comment by fmac2000** [comment]
Eloi you have my thanks, great work - if it would be possible to see a pre-print i'd love to read :)

http://research.spa.aalto.fi/publications/papers/dafx-babe2/

**Comment by eloimoliner** [comment]
Oh, cool that you noticed that. The pre-print will appear on arxiv later this week :)

**Comment by eloimoliner** [comment]
Hi! The pre-print is on archive already

https://arxiv.org/abs/2403.18636

**Comment by fmac2000** [comment]
It's another homerun Eloi, well done. I'll link the[ code here](https://github.com/eloimoliner/BABE2-music-restoration) for @B3AU and others who stumble across this.

Thanks Eloi, you and the team are exceedingly talented.
